-- CreateTable
CREATE TABLE "_prisma_migrations" (
    "id"                     TEXT PRIMARY KEY,
    "checksum"               TEXT NOT NULL,
    "finished_at"            TIMESTAMPTZ,
    "migration_name"         TEXT NOT NULL,
    "logs"                   TEXT,
    "rolled_back_at"         TIMESTAMPTZ,
    "started_at"             TIMESTAMPTZ NOT NULL DEFAULT now(),
    "applied_steps_count"    INTEGER NOT NULL DEFAULT 0
);
