server {
    listen 80;
    server_name 8.145.34.30 localhost;
    root /var/www/smart-kitchen;
    index index.html;

    location /api/ {
        proxy_pass http://backend:3001;
    }

    location / {
        try_files \ \/ /index.html;
    }
}
